---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-creds
  namespace: default
spec:
  encryptedData:
    password: AgCDRxBciu01CvcKpr6vefhMGWqpZJS4/OWDiVWjdMWVoXNd51HKpQLTadKmkYr/xKB1HixkqVreLWigCPvakEgKWj09Lu501wXfIfbNYjbGPIaZe0/8s+jEcySYnTBijkXl8xMVDh6wY51oe8erqpDjedcjho4i+4mScL+ycDhEP5ExRGUsehXkty+AlkBBJmBsGoGrZOX1NA2LFyWD8VGWLUvMp8fDxvDAa2edSQ7nPanM7X4VfSr7kJR228C5uGJhh22Vcf9i27IsrQgsRJ7efj1a3V2/w7ynOl8Hf8N8zuEQ/MyxK9I/cp8lmwPU1T6OKrWU+nqZgaFBc+mySVYulI1XE7po9XKlccA0x1s8T5FII9XfDP1rJLPtwdHBi5HyrV5tVmnf8PvH5AN/UOo2yZLwCGQucJH5K0tcouxKeiIdqT/zSa/xj5D3AlT2TNH9vRAVbfVW74Wjp2giwsOuO3U7K2MVGoGtllV0cEueX+SR/8IgoRQFaf7eH3Sz5KbDDYHiiD6gKcACgF6YQGo9sGvFueINIf8ny/2LCTd2UpJUV27KQunwWVUC95cxkmxgvUcdrktm50z3HhMQUO+0GzilBgtEe8QY83DuARX+cFAQH6Hc9QHnTgOWHK0wqPgCmDE3lIjMxe0SGVy0TpB/12Mc2+E+3eGKF5PuEBJPWQcgFpXaGxHfBIDi5Oq8QHg0YtVgFZJr
    username: AgAstWsYjv7RSCBHZHPfEtFrtUDvKHuKlFYZP1G7NJx00gOW1KPu5awy4eUUX2QPvy9wRAolszY+p923iHLz4dIufTW/5tsnu3YiEluvKUtKPjHSDFCOhHpZsnRI/SM1VdbpKXuEUkfuD3ZvzPvmGlY4EJbk13m3fz0TMcvjQlMszjcs6I4zeOCUNZBEHyjaNRa/0lORHyLKrPu9oCC+SeWg8raBoerQKtyJ0KUT+bsnrFPukQQvMKldnhqJL1YzW/165IXSsCVOgf1ti+InZYpVR2rDWAKAzFNF82wNEfJx/vMmjccygHPV2LTCSp3xsv22YLcnhHwuhCHmxxVMjj9pnCbeug2uIEwgL2T0bHrAWYbmwMZdorSdrSK5dwIsQKfym4ngCXJ5M+ynxMiGWRhR9I2TsdrURYspsGef9eATYAa9BpC0z0aDB7nteAwRWJekUqlEeGm+46E0pi1ZeCYVBSWjk2YcgjSYT5X38WaBGjl7VHYzHz8gXM6ZzAEgsNGjGeeutDC2XO/t/rah+iCtRwUpi7hujTC1gKves9J1N/aEYfEunAh43OLGKPTDrIx0mToWUi0IOF2pE5ZvTPD7BwAAibMyrLeXlTwEGofazjhqv6bJqkNT5CFPZVRD4BiU0MLWQOn3Qab01hCH3GzS3abWTqtqAWNWowLZFMUHOKda9DWxccePEolWQE1hV3n6wpILkg==
  template:
    metadata:
      creationTimestamp: null
      name: db-creds
      namespace: default
